"project_id": "658746"
"api_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJ3UUVxdmhVM3ZMT2EyWGljbVV5VCIsImp0aSI6ImIwMDRjNTY4NmNkZTI0MWUxYjI2NjFhN2M5YjI0ZmEyNzBiMDhkZmU1ZjZmNTRhOWRmNTk4YWRkMjU4YTEzMGExNjM0YTE3ZTIwYmU5YmM1IiwiaWF0IjoxNzExMDA2OTE5Ljg5NzMzOSwibmJmIjoxNzExMDA2OTE5Ljg5NzM0MSwiZXhwIjoxNzQyNTQyOTE5LjgzMjcwOCwic3ViIjoiMTYyNzM3MTAiLCJzY29wZXMiOlsicHJvamVjdCJdLCJkb21haW4iOm51bGwsImFzc29jaWF0aW9ucyI6WyIqIl0sInNlc3Npb24iOjB9.acMK9GJZu0QkyhAaHLk1agJUN7oiM1k0YjykbH-fo5TCfTOgdcO7u5FkNnKQFv9N7KLY90vrdKgnsAr8HiRgYN36hQ6l6d34VvtbSdMeQf-igpTHUSXhdUmqwhOYXaczpjycxCaTSN4ytTkxQZBrpDD5ko19ot-8eWASsdlVBdSr6yqAlapD0OKzmGhE55DNadUPVKqjWaS57Sptcwbl-TOKAsEAjEx7r45POyEEMR7FujNgj4tXaa4RtlF8V9x4dJBCr1Y1G-27st7WPGgsBMVjFk66_TWHkZniHUnNhM0i64zh85OFieQDjIlQfjWJ8Ved_kZ6kh1ozX8By72nzjNUUcRHkwl4Dg0ZBqHFN-M-RiZapmxm5FCz0TI7rUctcjt9vs9LuVuIkzohjHixQ9da_eKiYLwdJYDgNLmlWr_CnD2m0te2lnXvVS5DxMGBNPD8bxxl0qeccAetDxdFLsBSpGE8xGiUyQiCLh3jTKYMExhk-fXPaa3xV9w50WLb-uqoMnem7pc7QiLWa7jQoYef_V4knWSryjXEWJtuv3gu8YsgwxYVNDtDDfn39rQ9faxJv_W4QyTR8ZuIfjpPKZSz83-dUGbH8QCbiBtAsNa3KSA7XhQc6etxDU4-TxtVNwjOgfgWVNKi7WBTa9o1XPzKNh53YmuKTJbPK6mftZk"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
files:
  [
    {
      "source": "/messages/en.json",
      "translation": "/messages/%two_letters_code%.json",
    },
  ]
