"project_id": "658500"
"api_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJ3UUVxdmhVM3ZMT2EyWGljbVV5VCIsImp0aSI6IjBkMGQ1MDAyZDg0YWE1Y2I1YzdlODI4ZWYzNjFmZjFiZmM3YjczMGM3MzNmNmM0NTM3YzIxN2FmOTg2NmU3NGQ2NzkyYTQwNWY4ZGIwNDUzIiwiaWF0IjoxNzEwOTg2ODM2LjA3NDA4MiwibmJmIjoxNzEwOTg2ODM2LjA3NDA4NSwiZXhwIjoxNzQyNTIyODM1Ljk5OTc1MSwic3ViIjoiMTYyNzM3MTAiLCJzY29wZXMiOlsicHJvamVjdCJdLCJkb21haW4iOm51bGwsImFzc29jaWF0aW9ucyI6WyIqIl0sInNlc3Npb24iOjB9.fn6FKNHj7E29l1JKgCewk68eK14fkIAZDFznhWQuj131V-05-zQwseEnR1X0amh7RL0LhQeGMWJACdxwv8JAGWsYEDPeWBzdZW72kXVq5whGwBPNdPdl3gudLCaA3grm8jcOFQxQASZfcA5PAAW-fKXQ6qXbwF7wk76QdNQRoH1qZAiHvU2t_vCkIAsQQy6IFIi8ovdEePPJgr9pSa4qyhxIM8_g2iOhbX9Ok84BxKBOgOcA1ziMN-h8DgQoDKsuUV9220TwG04rmEYrD5IqjzRmA-UJxGHBV0C4bM2uP9oHbk3U_tvn6TZLzumvTseb54Qr8O_B1giK1gq4cRfkPCiGBd3JcUla8gYPGhvKMxppV2LzL91Ly8H4O40Jtj2d5KyTsvnj5Vh4YfHqDFw__1w_i6afz6gFtw2cgKchh60m90lbjS_s3rj8P8-O_ejLcQl4tf0zqqCjcqCEfQsZhMO507GFpLaMqPXPc4iK6vlIUxeKoF9QFFMIx_YqIwJ82UTWDJW9PyxcO9qE9W0EbZo5u1PCCRv69H2IFBE9Iq9GAyYCJ2Hjw06GfirsPj8srNylGEJtIvJ23rKR_eUsE0_xzUu8tgYtR9dkzKyfpXeqPxZyk8DiL3NxUx-F3tAGQw3LQi2IyNufgB5KZMT8ykkZjxLOU4VH0zUowHkdxVQ"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
files:
  [
    {
      "source": "/messages/en.json",
      "translation": "/messages/%two_letters_code%.json",
    },
  ]
